table 'Opportunity Calendar'
	lineageTag: f05ebaf6-164a-4645-bd29-251d3858ef11

	column Date
		dataType: DateTime
		formatString = General Date
		lineageTag: f8f8c0be-e576-44fd-9ee5-23cce4263a28
		summarizeBy: None
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column MONTH
		dataType: String
		lineageTag: ece623e2-fde5-4a99-bb04-108a45b85480
		summarizeBy: None
		sourceColumn: MONTH

		annotation SummarizationSetBy = Automatic

	column 'RELATIVE 07 DAY PERIOD'
		dataType: Int64
		formatString = 0
		lineageTag: 473b14be-d53e-41de-b70c-b17050d3ff4a
		summarizeBy: None
		sourceColumn: RELATIVE 07 DAY PERIOD

		annotation SummarizationSetBy = Automatic

	column 'RELATIVE 30 DAY PERIOD'
		dataType: Int64
		formatString = 0
		lineageTag: 14974f1e-7342-4901-aec3-58dc18b3f52d
		summarizeBy: None
		sourceColumn: RELATIVE 30 DAY PERIOD

		annotation SummarizationSetBy = Automatic

	column 'RELATIVE DAY'
		dataType: DateTime
		formatString = General Date
		lineageTag: 7e288c06-2f9f-48e0-a7e2-330ab90131c4
		summarizeBy: None
		sourceColumn: RELATIVE DAY

		annotation SummarizationSetBy = Automatic

	column 'RELATIVE MONTH'
		dataType: Int64
		formatString = 0
		lineageTag: b9573798-fc36-4ea6-a399-447eccf42288
		summarizeBy: None
		sourceColumn: RELATIVE MONTH

		annotation SummarizationSetBy = Automatic

	column 'RELATIVE WEEK'
		dataType: Int64
		formatString = 0
		lineageTag: 775bf6bd-b2ed-450e-a37f-be869a2cfd08
		summarizeBy: None
		sourceColumn: RELATIVE WEEK

		annotation SummarizationSetBy = Automatic

	column WEEK
		dataType: DateTime
		formatString = General Date
		lineageTag: e29dc755-1566-4963-aea1-5ab3eae34a02
		summarizeBy: None
		sourceColumn: WEEK

		annotation SummarizationSetBy = Automatic

	column YEAR
		dataType: Int64
		formatString = 0
		lineageTag: 52e642ff-1c13-4791-8699-54bfa21c1fe2
		summarizeBy: None
		sourceColumn: YEAR

		annotation SummarizationSetBy = Automatic

	column 'YEAR MONTH'
		dataType: DateTime
		formatString = Long Date
		lineageTag: a2f4ec13-260a-474a-9e06-d5c83b2b83a3
		summarizeBy: None
		sourceColumn: YEAR MONTH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'YEAR WEEK'
		dataType: String
		lineageTag: b8110457-e56a-4cc1-8f70-72f89bf455ee
		summarizeBy: None
		sourceColumn: YEAR WEEK

		annotation SummarizationSetBy = Automatic

	column DAY
		dataType: DateTime
		formatString = General Date
		lineageTag: 5f9f4561-e52f-4681-a285-65f5fe9b295e
		summarizeBy: None
		sourceColumn: DAY

		annotation SummarizationSetBy = Automatic

	column DaySeq
		dataType: Int64
		formatString = 0
		lineageTag: 1d98460f-7278-40c9-8903-be2bd28ffd3c
		summarizeBy: None
		sourceColumn: DaySeq

		annotation SummarizationSetBy = Automatic

	column 'MONTH NUMBER'
		dataType: Int64
		formatString = 0
		lineageTag: c11064fc-442b-4deb-8cf9-16ed706b6d8f
		summarizeBy: None
		sourceColumn: MONTH NUMBER

		annotation SummarizationSetBy = Automatic

	column 'YEAR MONTH NUMBER'
		dataType: Int64
		formatString = 0
		lineageTag: 36c2cd16-c054-42be-9d6b-dedb6fbaaa70
		summarizeBy: None
		sourceColumn: YEAR MONTH NUMBER

		annotation SummarizationSetBy = Automatic

	partition 'Opportunity Calendar-e96137a3-9df6-439b-a40b-8871bb9ea948' = M
		mode: Import
		expression =
			let
			    Source = Excel.Workbook(File.Contents("C:\Users\chamil\Desktop\Opportunity calendar.xlsx"), null, true),
			    #"Date table for stores_Sheet" = Source{[Item="Date table for stores",Kind="Sheet"]}[Data],
			    #"Promoted Headers" = Table.PromoteHeaders(#"Date table for stores_Sheet", [PromoteAllScalars=true]),
			    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type datetime}, {"MONTH", type text}, {"RELATIVE 07 DAY PERIOD", Int64.Type}, {"RELATIVE 30 DAY PERIOD", Int64.Type}, {"RELATIVE DAY", type datetime}, {"RELATIVE MONTH", Int64.Type}, {"RELATIVE WEEK", Int64.Type}, {"WEEK", type datetime}, {"YEAR", Int64.Type}, {"YEAR MONTH", type date}, {"YEAR WEEK", type text}, {"DAY", type datetime}, {"DaySeq", Int64.Type}, {"MONTH NUMBER", Int64.Type}, {"YEAR MONTH NUMBER", Int64.Type}})
			in
			    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_ChangedProperties = ["Name"]

